spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      #properties:
    #hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST:localhost}:9092

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_SERVER_HOST:localhost}:5432/${POSTGRES_DB_NAME:training}
    username: postgres
    password: ${POSTGRES_DB_PASSWORD:Cloud@123$}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 7075

management:
  endpoints:
    web:
      exposure:
        include: "*"
