spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST:localhost:9092}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 7077

management:
  endpoints:
    web:
      exposure:
        include: "*"
